
print('Vou ler a sua mente!')
input()
input('Pense em um número:')
input()
print('Multiplica por 2:')
input()
print('Some mais 10:')
input()
print('Divida por 2:')
input()
print('Menos o número que você pensou: ')
input()
print('O resultado é 5!')
   